### ISSUE TITLE
Redis Validation Issue

### ISSUE THREAD

**Issue by KiwiFroots** [gustav9797/PowerfulPerms#11]
I know this is probably not a PowerfulPerms thing as such, and is probably my server, but I've tried everything so far, but to no avail. Happens on both bungee and spigot, and unable to `service redis restart` or even remove redis from the system at all, so, last hope, I guess.. :)

Bungee Error: https://hastebin.com/oloxinefel.rb
Spigot Error: https://hastebin.com/udiqupamil.vbs

Happens when keys are fetched and when a pp command is executed.. 

Any help would be greatly appreciated,
- Kiwi

**Comment by gustav9797** [comment]
Hello is this solved?

**Comment by KiwiFroots** [comment]
Yes, thanks
