### ISSUE TITLE
Importing in eclipse.

### ISSUE THREAD

**Issue by BrowkTQ** [gustav9797/PowerfulPerms#8]
Hello. I wanna modify some features for my server, in eclipse, but I don't know how to import your project. Can you help me, please?

**Comment by sebastianbinder** [comment]
Google (took me 30 seconds) -> https://books.sonatype.com/m2eclipse-book/reference/creating-sect-importing-projects.html

**Comment by BrowkTQ** [comment]
I tried this tutorial, but didin't work. This is what I did:
- I downloaded PowerfulPerms-master archive. (from https://github.com/gustav9797/PowerfulPerms)
- I tried to import it using this: http://prntscr.com/gwkxux
But, when I try to export this resource, it gives me an error: http://prntscr.com/gwkyjp
Also, imports (in code) don't work.
Example: http://prntscr.com/gwkzad

**Comment by sebastianbinder** [comment]
Many changes have been done in the last couple of hours. Please redownload and try again.
